#!/bin/bash
directoryName=$(dirname $(realpath $0))
if ! [ -d $directoryName/eclipse4learnjglut-linux ]; then
	cd $directoryname
	wget https://github.com/pflagerd/learnjglut/releases/download/0.1.0/eclipse4learnjglut-linux.tar.gz
	tar xzf eclipse4learnjglut-linux.tar.gz
	rm eclipse4learnjglut-linux.tar.gz	
fi

cd $directoryName/eclipse4learnjglut-linux
./eclipse >> $directoryName/eclipse4learnjglut-linux/eclipse4learnjglut-linux.log 2>&1 &
